### ISSUE TITLE
Hi! I have a little problem.

### ISSUE THREAD

**Issue by xhzengAIB** [robbykraft/Social#1]
Hi! @robbykraft 

I run this project, when i input building code, what's building code? i have no idea it's form where?

Jack

**Comment by xhzengAIB** [comment]
i write the ApplicationId and clientKey in your code.

**Comment by robbykraft** [comment]
Hi Jack,
Sorry, this is a project for a client, and I need to be closing access to this repo. The building code is a part of their project, I'm not allowed to pass along the access.
Hope this at least got you started with Parse! Good luck!

**Comment by xhzengAIB** [comment]
Hi! @ robbykraft
Thank you for your kind reply, I want to study here the UI and patterns, then I close the issue!

Jack
